name: Build

on:
  push:
    branches: ["bugfix/nuget"]
  pull_request:
    branches: ["bugfix/nuget"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install node dependencies
        working-directory: SCE.Core/assets
        run: |
          npm install
      - name: Build dotnet
        run: dotnet build --configuration Release # /WarnAsError
      - name: pack dotnet
        run: dotnet pack SCE.Core/SCE.Core.csproj --configuration Release
